swagger:
  enable: true

security:
  enable: false
  ex-path: /auth/register,/auth/login,/swagger-resources/**,/swagger-ui.html,/v2/api-docs,/webjars/**

token:
  alive-time: 3600

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/frame?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      filters: stat,wall # 底层开启功能，stat（sql监控），wall（防火墙）
      filter: # 对上面 filters 详细配置
        slf4j:
          enabled: true # 开启日志功能
        wall:
          enabled: true # 开启防火墙功能
          config:
            drop-table-allow: false
        stat:
          enabled: true # 开启sql监控功能
          slow-sql-millis: 1000  # 配置SQL慢的标准
          log-slow-sql: true # 是否开启记录执行慢的sql
      stat-view-servlet:
        enabled: true # 开启监控页功能
        login-username: tr # 监控页登录账号
        login-password: 123456 # 监控页登录密码
        reset-enable: false # 配置是否允许重置监控信息
      web-stat-filter:
        enabled: true # 开启web监控
        urlPattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # web监控白名单
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000   # 连接超时
    jedis:
      pool:
        type: jedisPool
        max-wait: 1000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 2000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 300     # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接

mqtt:
  url: tcp://153.37.213.2:1883
  username: user
  password: 123456
  clientId: frame_mqtt_client
  topic: topic0,topic1,topic2
  qos: 0,1,2 # 与上面的 topic 一一对应
  defaultTopic: default_topic
  defaultQos: 0
  completionTimeout: 3000
  automaticReconnect: true # 断开连接重新连接
  cleanSession: true
  retained: false